version: 2
jobs:
  build:
    docker:
        - image: circleci/node:13-browsers
          environment:
            CHROME_BIN: "Program Files (x86)\Google\Chrome\Application\Chrome.exe"
    steps:
        - checkout
        - run:
            name: Update npm
            
        - restore_cache:
            key: dependency-cache-{{ checksum "package.json" }}
        - run:
            name: Installing dependencies (npm install)
            command: npm install
        - save_cache:
            key: dependency-cache-{{ checksum "package.json" }}
            paths:
              - node_modules
        - run:
            name: npm run test:coverage
            command: npm run test:coverage
        - run:
            name: npm run lint
            command: npm run lint
        - store_artifacts:
            path: dist
            prefix: dist

workflows:
  version: 2
  test:
    jobs:
      - build