jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - browser-tools/install-browser-tools:
          install-chrome: true 
          chrome-version: '102.0.5005.115' 

workflows:
  example-workflow:
    jobs:
      - example-job